"""init

Revision ID: 4e1983ae72b6
Revises: e97d8983d4be
Create Date: 2024-11-21 17:18:57.862685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1983ae72b6'
down_revision = 'e97d8983d4be'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
