"""init

Revision ID: 5d73e2401160
Revises: bf0f861a582f
Create Date: 2024-11-25 18:20:22.262287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d73e2401160'
down_revision = 'bf0f861a582f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('base_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testtable'))
    )
    op.create_index('test_index', 'testtable', ['name'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('test_index', table_name='testtable')
    op.drop_table('testtable')
    # ### end Alembic commands ###
