"""init

Revision ID: e97d8983d4be
Revises: ce4a5d30f647
Create Date: 2024-11-21 16:59:41.457146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97d8983d4be'
down_revision = 'ce4a5d30f647'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
