"""init

Revision ID: bf0f861a582f
Revises: be5611ef11a0
Create Date: 2024-11-21 17:31:56.070801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0f861a582f'
down_revision = 'be5611ef11a0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
