"""init

Revision ID: be5611ef11a0
Revises: 4e1983ae72b6
Create Date: 2024-11-21 17:23:57.975593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5611ef11a0'
down_revision = '4e1983ae72b6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
