"""init

Revision ID: 9049e3728b9c
Revises: 5d73e2401160
Create Date: 2025-01-01 17:23:44.167067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9049e3728b9c'
down_revision = '5d73e2401160'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
