"""init

Revision ID: 7531bb5a9412
Revises: 5ea27c3d2631
Create Date: 2025-01-01 19:04:39.455158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7531bb5a9412'
down_revision = '5ea27c3d2631'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
