"""init

Revision ID: b3d6317f3820
Revises: 56a9fcbc9102
Create Date: 2025-01-05 17:28:31.296463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d6317f3820'
down_revision = '56a9fcbc9102'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template_header', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('class_template', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('method_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'method_template')
    op.drop_column('templates', 'class_template')
    op.drop_column('templates', 'template_header')
    # ### end Alembic commands ###
