"""Testing update of schema

Revision ID: 1537e48616dd
Revises: 9049e3728b9c
Create Date: 2025-01-01 17:32:10.238581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1537e48616dd'
down_revision = '9049e3728b9c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testtable', 'age')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testtable', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
