"""Attempting to update DB to relational 10

Revision ID: 5ea27c3d2631
Revises: 1e0846d34be2
Create Date: 2025-01-01 19:03:56.554619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea27c3d2631'
down_revision = '1e0846d34be2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_pass', sa.String(length=100), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.add_column('templates', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_templates_user_id_users'), 'templates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_templates_user_id_users'), 'templates', type_='foreignkey')
    op.drop_column('templates', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
