"""init

Revision ID: 56a9fcbc9102
Revises: 7531bb5a9412
Create Date: 2025-01-01 19:13:44.611073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a9fcbc9102'
down_revision = '7531bb5a9412'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
