"""Attempting to update DB to relational7

Revision ID: f88af3693837
Revises: 1537e48616dd
Create Date: 2025-01-01 18:48:03.325155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88af3693837'
down_revision = '1537e48616dd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index('id', 'templates', ['id'], unique=True)
    op.drop_index('test_index', table_name='testtable')
    op.drop_table('testtable')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_testtable')
    )
    op.create_index('test_index', 'testtable', ['name'], unique=True)
    op.drop_index('id', table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
