"""Attempting to update DB to relational 8

Revision ID: 1e0846d34be2
Revises: f88af3693837
Create Date: 2025-01-01 18:56:07.994728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0846d34be2'
down_revision = 'f88af3693837'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
